### ISSUE TITLE
Homebridge-nest crashing homebridge (this just started happening)

### ISSUE THREAD

**Issue by leoneleone** [KraigM/homebridge-nest#106]
/usr/local/lib/node_modules/homebridge-nest/node_modules/firebase/node_modules/faye-websocket/node_modules/websocket-driver/node_modules/websocket-extensions/lib/websocket_extensions.js:133
    this._pipeline.processIncomingMessage(message, callback, context);
                  ^

TypeError: Cannot read property 'processIncomingMessage' of undefined
    at Extensions.processIncomingMessage (/usr/local/lib/node_modules/homebridge-nest/node_modules/firebase/node_modules/faye-websocket/node_modules/websocket-driver/node_modules/websocket-extensions/lib/websocket_extensions.js:133:19)
    at Client._emitMessage (/usr/local/lib/node_modules/homebridge-nest/node_modules/firebase/node_modules/faye-websocket/node_modules/websocket-driver/lib/websocket/driver/hybi.js:442:22)
    at Client._emitFrame (/usr/local/lib/node_modules/homebridge-nest/node_modules/firebase/node_modules/faye-websocket/node_modules/websocket-driver/lib/websocket/driver/hybi.js:405:19)
    at Client.parse (/usr/local/lib/node_modules/homebridge-nest/node_modules/firebase/node_modules/faye-websocket/node_modules/websocket-driver/lib/websocket/driver/hybi.js:144:18)
    at Client.parse (/usr/local/lib/node_modules/homebridge-nest/node_modules/firebase/node_modules/faye-websocket/node_modules/websocket-driver/lib/websocket/driver/client.js:56:58)
    at IO.write (/usr/local/lib/node_modules/homebridge-nest/node_modules/firebase/node_modules/faye-websocket/node_modules/websocket-driver/lib/websocket/streams.js:80:16)
    at TLSSocket.ondata (_stream_readable.js:555:20)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at TLSSocket.Readable.push (_stream_readable.js:134:10)
    at TLSWrap.onread (net.js:543:20)

**Comment by rglink** [comment]
+1 got the exact same issue. Looks like an issue communicating with Nest. Did they change the API, or is API not working properly?

**Comment by leoneleone** [comment]
I think it must've been something going on with the Nest servers. Seems to have corrected itself now. Homebridge started running again 👍🏼

I hadn't changed anything at all. 
Possibly best to close this issue as it was an issue on the Nest-end rather than the plugin 🙂

**Comment by leoneleone** [comment]
Closing

**Comment by leoneleone** [comment]
Ok. So this has started happening again today 😔

**Comment by leoneleone** [comment]
Anyone else seeing this error? 
What is going on with the Nest servers?!

This is quite frustrating

**Comment by tsm4sh** [comment]
all good for me...

**Comment by leoneleone** [comment]
@tsm4sh 
Thanks for letting me know 🙏 
I'll have to check my setup to find out what's going on.

**Comment by tsm4sh** [comment]
@leoneleone, I suggest removing/uninstalling the nest plugin and any others you may have installed, then uninstall homebridge as well, and reinstall homebridge and the plugins. I had to do that at one point when I started messing with all this stuff and it seemed to clear out some gremlins. Note, I'm also running v6.9.4 of Node.js, on macOS Sierra, not the newer v7.4.0.

**Comment by davidtennant8082** [comment]
Not sure what I was running when the issue arises as I haven't updated anything since I got homebridge working. 

Nuked everything this morning to troubleshoot and installed from scratch and issue. Removed all but login and password from the config file to fall back on legacy API. Have nothing else running on Homebridge other than 1 nest thermostat.

**Comment by tjq100** [comment]
I've got the same thing.  Been fine till today.

**Comment by rglink** [comment]
Yep, not working anymore.

**Comment by leoneleone** [comment]
@tsm4sh 
Thanks for the advice. 
I've removed homebridge from my HomeKit Configuration. Will try and complete reinstall tomorrow. 
I'm running Node 6.6.0 so might upgrade that. 

This has happened to me once before, and hours later homebridge starting working again. That's why I suspect it's an issue happening with the Nest servers rather than homebridge itself. 

Will let you know if anything works out.

**Comment by leoneleone** [comment]
@rglink @tjq100 
You might want to try just leaving it be without any tinkering to see if the problem corrects itself. Frustrating I know. Just shows how HomeKit functions quickly become part of the daily routine. Once that's broken things seem far more cumbersome. 
First world problems ultimately 😬 

Let me know if anything changes guys.

**Comment by randyinla** [comment]
This is also the 2nd time this has happened to me and it is still not working, so I removed homebridge-nest from my homebridge config.js file.

Maybe the nest plugin could add some error handling to the processIncomingMessage function to deal with an undefined response rather than crashing and causing homebridge to quit?  Would be much nicer to sense an undefined response and simply put something in the output log.  That way, all of my other homebridge devices still work.

**Comment by alexandrupaulpopa** [comment]
Still happening. It's on the Nest servers side

**Comment by mroffbeat** [comment]
lol, another reminder to check git first :)
I removed / reinstalled all files.. did not work

**Comment by PencilDH** [comment]
Hey Guys, this seems to be happening to quite a free people, does anyone understand the underling issue or debugged it?

If we are sure this is a Nest issue we should report it to Nest as we are developers to be looked at?! there is more than 10~20 people with the same issue that happens intermitently.

As suggest @Muzach on another issue #107 the script should also be made more robust to handle this errors rather than crashing

**Comment by rglink** [comment]
I agree on the error processing part, but haven't had the time to reply. 

Very much looks like a communication issue since the issue occurs in the pipeline incoming message from nest. Also since the issue sometimes resolves itself doesn't make it a clear scripting issue.

Looking forward to how this thread evolves...

**Comment by conradhagemans** [comment]
For now I removed the Nest platform in config.json of Homebridge. Homebridge runs again fine.
Hopefully there will be an update of the NPM Nest module.

**Comment by pmvrmc** [comment]
I am having the same issue, I hope they fix it soon...

**Comment by rtoohil** [comment]
For what it's worth, I don't think I would have closed this. The issue is still open -- without code fixes, the plugin doesn't work.

I'm still hoping I can find a few minutes to test out changing to a newer version of firebase (which will pull in a newer version of the websocket plugin), which I think we've shown does fix the issue. I'm just not sure if there are breaking/non-backwards compatible changes in the newer version of firebase.

**Comment by pmvrmc** [comment]
Unfortunately firebase 3.0 has breaking changes, and 2.X has an outdated version of the "faye-websocketa" dependency.

For more info look into this [pull request](https://github.com/faye/websocket-extensions-node/pull/3).

I fixed this issue by having an automated process that goes to the firebase dependency "faye-websocketa" and changes its package.json to use version of "websocket-driver"  >=0.5.4.

I hope this helps!

**Comment by rtoohil** [comment]
So, I think given that, it might make sense to use npm shrinkwrap. That'd be a pretty simple commit/pull request, and it should be a reasonable solution in the short-term.

**Comment by tekkkon** [comment]
yes, nest firebase is not catching up to 3.x and it is using 2.4.x which has dependency on "faye-websocket" -> "websocket-driver@0.5.1"

to fix the issue, you need to bump up the "websocket-driver>=0.5.2", using the latest 0.6.5 works for me

**Comment by simonrb2000** [comment]
Mine has stopped working with the fix... Was working until about an hour ago. Now loading Homebridge it stops..

`[1/13/2017, 7:35:50 PM] Loaded plugin: homebridge-nest
[1/13/2017, 7:35:50 PM] Registering platform 'homebridge-nest.Nest'
[1/13/2017, 7:35:50 PM] ---
[1/13/2017, 7:35:50 PM] Loaded plugin: homebridge-rasppi-gpio-garagedoor
[1/13/2017, 7:35:50 PM] Registering accessory 'homebridge-rasppi-gpio-garagedoor.RaspPiGPIOGarageDoor'
[1/13/2017, 7:35:50 PM] ---
[1/13/2017, 7:35:50 PM] Loaded config.json with 1 accessories and 1 platforms.
[1/13/2017, 7:35:50 PM] ---
[1/13/2017, 7:35:50 PM] Loading 1 platforms...
[1/13/2017, 7:35:50 PM] Initializing Nest platform...
[1/13/2017, 7:35:50 PM] Fetching Nest devices.
[1/13/2017, 7:35:50 PM] Loading 1 accessories...
[1/13/2017, 7:35:50 PM] [Garage Door] Initializing RaspPiGPIOGarageDoor accessory...
[1/13/2017, 7:35:50 PM] [Garage Door] Door Switch Pin: 4
[1/13/2017, 7:35:50 PM] [Garage Door] Door Sensor Pin: 14
[1/13/2017, 7:35:50 PM] [Garage Door] Door Poll in ms: 4000
[1/13/2017, 7:35:50 PM] [Garage Door] Door Opens in seconds: 20
[1/13/2017, 7:35:50 PM] [Garage Door] Setting state to 1`

**Comment by rtoohil** [comment]
Still works for me -- I've had to restart it once, but that was it.

**Comment by leoneleone** [comment]
@tekkkon 
Glad its working for you. I'm still having problems here.

can you give us some instructions for how you bumped up the "websocket-driver>=0.5.2", using the latest 0.6.5?

**Comment by leoneleone** [comment]
So everything seems to be working as normal now since updating to the latest version of Homebridge which was published yesterday. I'll have to give it more time to see if the fire base errors appears again to be sure. 

Can anyone confirm that the latest version of homebridge fixes the issue for them? 
If so I could close the issue.... 

Thanks everyone

**Comment by rtoohil** [comment]
https://github.com/KraigM/homebridge-nest/pull/109

I don't see why homebridge's update would have fixed the problem.

If you want to test my fix, you could clone the homebridge-nest repo somewhere on your homebridge server, checkout my branch, and then run the plugin in debug mode. Or, copy the npm-shrinkwrap.json over and run npm install.

It'll be easiest if the pull request gets merged in, since that should get it up and running for everyone (I think).

**Comment by simonrb2000** [comment]
Mine is working again, just took the Nest plugin out of config, left it running over night then this morning I put it back in. Strange!!! Maybe Nest were having a problem as only thing I changed was the config file.

I had updated the webscoket and worked until yesterday - working now after leaving it overnight.

Cheers

On 14 Jan 2017, at 11:59, Ryan Toohil <notifications@github.com<mailto:notifications@github.com>> wrote:


#109<https://github.com/KraigM/homebridge-nest/pull/109>

I don't see why homebridge's update would have fixed the problem.

If you want to test my fix, you could clone the homebridge-nest repo somewhere on your homebridge server, checkout my branch, and then run the plugin in debug mode. Or, copy the npm-shrinkwrap.json over and run npm install.

It'll be easiest if the pull request gets merged in, since that should get it up and running for everyone (I think).

-

**Comment by rglink** [comment]
Mine has been working without updating any modules. To overcome the crashing when no correct incoming message is found I created an AppleScript that restarts homebridge once every hour. Also the issue started without any software changes and beforehand mine worked for over a year. So I am not sure that a script needs to be replaced. Only error handling could be better so homebridge doesn't crash. Will the hotfix fix this issue?

**Comment by leoneleone** [comment]
@simonrb2000 
Thanks for the info. 
Yes I agree, there's no logical reason why updating homebridge would fix the firebase/websocket issue. Could just be a coincidence, but I haven't had an issue since updating despite having had to restart homebridge several times today because of a separate internal home networking issue.
