### ISSUE TITLE
Support for switching away and home modes

### ISSUE THREAD

**Issue by Raxaco** [KraigM/homebridge-nest#15]
I just downloaded version 0.1.1 of the plugin and had a great time changing thermostat settings with siri. Thanks!

I noticed that the "I'm home" and "I'm leaving" voice commands don't set the nest mode to home and away. When I said "I'm leaving" Siri replied "Sorry Raxaco, I wasn't able to find any devices this time" 
When I said "I'm home" she welcomed me back but the away/home mode stayed on "away."

I have homebridge@0.2.11 and homebridge-nest@0.1.1

**Comment by KraigM** [comment]
Just to make sure, you did configure the "I'm home" / "I'm leaving" to change the away status?

**Comment by Raxaco** [comment]
No, how do you do that?

**Comment by KraigM** [comment]
"I'm home" / "I'm leaving" are default scene's Apple creates for you, so you just have to add it to those scenes. 

How depends on what app you are using to control HomeKit.  Normally I use [Insteon+](https://itunes.apple.com/us/app/insteon+/id919270334?mt=8) because the interface is so nice.  But in this case I had to use  [Elgato Eve](https://itunes.apple.com/us/app/elgato-eve/id917695792?mt=8).  

On Elgato Eve (from the first screen):
 1. Click the settings "cog" in the top right corner
 2. Scenes
 3. "I'm Home"
 4. Add Actions 
 5. You should find an _Away_ type at the bottom (which is our custom type), open it
 6. Enable it for your Nest
 7. Chose OFF (to signify not away)
 8. Repeat using "I'm leaving" for step 3 and "ON" for step 7

**Comment by KraigM** [comment]
It doesn't matter which HomeKit app you use to change it, it will effect HomeKit itself.  They all just change settings on the HomeKit API that iOS manages.

**Comment by Raxaco** [comment]
Aha! Thanks!
