### ISSUE TITLE
New API Setup

### ISSUE THREAD

**Issue by vanhoutem** [KraigM/homebridge-nest#22]
When following the instructions in "How to Setup New API" there are a couple of issues:

1. In step 8, the name "HomeBridge" is not allowed as it already exists. I did use a different name but don't know if this will cause problems.

2. After step 12, there is no option to "Accept the terms and copy the Pin Code". The error message "CODE IS ONLY VALID ONCE!" does not appear.

**Comment by KraigM** [comment]
No what you did with step 8 is fine (what everyone else did)

**Comment by KraigM** [comment]
In step 12, you have to use your browser to navigate to that URL.  Once you do you should see a tan page that asks you if you authorize the api you created to access your system (you may have to login first but if you setup your dev account with your main account then you should already be logged in).  Once you hit accept it will give you a pin code (a bunch of big numbers in blocks) instead of a redirect (assuming you didn't specify a redirect URL).  

Once you have the pin code and added to the config (step 13), THEN you continue to step 14 which involves using that code so you get the message "CODE IS ONLY VALID ONCE!"

**Comment by vanhoutem** [comment]
Thanks for your assistance, got it working now  :)

It wasn't clear to me that I had to open the URL in another browser window. Another hurdle I encountered was caused my me trying to start Homebridge with the token copied from the example config instead of with an empty token. Newbie and all.

Thanks again!
