### ISSUE TITLE
Error checking on request-promise

### ISSUE THREAD

**Issue by rudders** [KraigM/homebridge-nest#25]
Hi,

There has been a niggling issue over in Homebridge (https://github.com/nfarina/homebridge/issues/457) that was potentially caused by homebridge-platform-wemo (https://github.com/rudders/homebridge-platform-wemo). We tracked it down to some error checking in a dependent module wemo-client. It wasn' handling errors well on an httpRequest essentially.

The user that reported the issue @AppleTechy (https://github.com/AppleTechy) (well one of them) continues to have a similar problem caused by an underlying HTTP failure (ETIMEOUT), He also has homebridge-nest installed and his debug log shows next activity just before the error. 

I was wondering of some of the error checking that is available on request-promise (https://github.com/request/request-promise#get-a-rejection-only-if-the-request-failed-for-technical-reasons) might be applicable in homebridge-nest. 

I can't try and fix it as we don't even have Nest Thermos in Australia....

**Comment by KraigM** [comment]
@AppleTechy thinks it may be his router.  He updated the his firmware and hasn't received it since. 

Request-Promise does have a catch system (.catch) which we redirect to HomeBridge. 

That being said if it was an issue with TCP from the Nest plugin (on the new API) it would have had a bunch of firebase errors around it.
