### ISSUE TITLE
Plugin breaks homebridge if it can't communicate with NEST API

### ISSUE THREAD

**Issue by pinballnewf** [KraigM/homebridge-nest#30]
If the NEST plugin cannot communicate with the NEST cloud/API due to blocked firewall ports, homebridge never finishes initializing [doesn't display the PIN window] and all devices/accessories become unavailable.  No error is logged to the console to inform user, homebridge hangs.

**Comment by KraigM** [comment]
Im not sure on that one.  I know home bridge obviously waits for us to figure out what devices we have before starting.  We can't just register the devices later unfortunately (since home bridge does not support dynamically added/removed devices).  So if you want Nest (i.e. the Nest plugin is installed and configured) then we have to establish a connection.  Otherwise I think you loose all the setup you did with those devices in HomeKit (renaming, assign to rooms, modifying in scenes, etc).

Now as far as how to fix/investigate your firewall issues.  Try going in debug or full debug mode.

**HomeBridge Debug:** `homebridge -D`

**Full Debug:** `DEBUG=* homebridge -D`

**Comment by pinballnewf** [comment]
I opened the firewall and all is happy.  I did have to open the ports for the NEST itself to work [ironically, the NEST claimed it was online, but the web portal said it was offline].

I did use Homebridge debug [not full debug though] and no additional errors were displayed.  I guess my concern is failure to initialize homebridge-nest shouldn't prevent everything else from coming up, or at least timeout with an displayed error after a few seconds and let startup proceed with '0' NEST devices. 

When I first configured homebridge-nest I couldn't figure out why homebridge had now completely 'failed' and could no longer be seen.  I went as far as to erase everything and reload only to have the same trouble, not ever thinking failure to communicate by the new plugin would prevent startup, and not immediately coming to the obvious conclusion that the plugin would need the same firewall config as the device itself.

Maybe the 'fix' is as simple as a note in the install instructions noting that if your homebridge becomes invisible and no longer shows the pin pairing screen on startup that you must check NEST communications.  This may prevent anyone else running into this from resetting their whole config.

**Comment by KraigM** [comment]
If we just give up and return no devices (as suggested) then any config you have done on that device in HomeKit will be wiped.  And there is no way for us to add it back in after HomeBridge has been started (currently).  You can obviously remove the Nest platform from your HomeBridge config and it would let you start.

All that being said, hopefully in the near future we will be able to switch to the weave API, which wouldn't have to worry about internet facing firewalls, as it works on the internal network.

**Comment by KraigM** [comment]
If there is anything else or if I missed something, feel free to reopen this.
